  function smoothedVC = getSmoothedVertices(vc, VertConn, smoothValue)
        smoothValue = smoothValue/100;
       
            iVertices = 1:size(vc,1);
            % 计算平滑迭代次数（与PlotSource一致）
            SurfSmoothIterations = ceil(300 * smoothValue * length(iVertices) / 100000);
            % 调用tess_smooth计算平滑后的顶点
            smoothedVC = vc;
            smoothedVC(iVertices,:) = tess_smooth(...
                vc(iVertices,:), ...
                smoothValue, ...
                SurfSmoothIterations, ...
                VertConn(iVertices,iVertices), ...
                1 ...
                );
        end