function reg = seal_getAlgorithmRegistry()
% 每个算法 = 一份配置；新增算法只改这里
% parent: 'minL2' | 'spatio' | 'sparse'
% params: 每个参数 = {字段名, 显示标签, 控件类型, 默认值, [选项]}

reg = struct();

reg.MNE = struct( ...
    'parent','minL2', ...
    'title','MNE Settings', ...
    'params',{{
    {'RegularizationParameter','RegParam','numeric',0.1}
    {'sourceCovariance','SourceCov','edit','depth_weighted'}
    }});

reg.dSPM = struct('parent','minL2','title','dSPM Settings','params',{{
    {'RegularizationParameter','RegParam','numeric',0.1}
    }});

reg.sLORETA = struct('parent','minL2','title','sLORETA Settings','params',{{
    {'RegularizationParameter','RegParam','numeric',0.1}
    {'sourceCovariance','SourceCov','edit','depth_weighted'}
    }});

reg.eLORETA = struct('parent','minL2','title','eLORETA Settings','params',{{ ...
    {'sourceCovariance','SourceCov','edit','depth_weighted'} ...
    {'MaxIterations','MaxIterations','numeric',100} ...
    {'Tolerance','Tolerance','numeric', 1e-6} ...
    }});

reg.LORETA  = struct('parent','minL2','title','LORETA Settings','params',{{ ...
    {'RegularizationParameter','RegParam','numeric',0.1} ...
    {'DepthWeightingExponent','DepthWeightingExponent','numeric',1} ...
    {'LaplacianRegFactor','LaplacianRegFactor','numeric',1e-4} ...
    {'sourceCovariance','SourceCov','edit','depth_weighted'} ...
    }});

reg.LAURA   = struct('parent','minL2','title','LAURA Settings','params',{{ ...
    {'RegularizationParameter','RegParam','numeric',0.1} ...
    {'DepthWeightingExponent','DepthWeightingExponent','numeric',1} ...
    {'Exponent_e_LAURA','Exponent_e_LAURA','numeric',2} ...
    {'MaxNeighborsN_LAURA','MaxNeighborsN_LAURA','numeric',9}
    }});

reg.LOGURA   = struct('parent','minL2','title','LOGURA Settings','params',{{ ...
    {'RegularizationParameter','RegParam','numeric',0.1} ...
    {'DepthWeightingExponent','DepthWeightingExponent','numeric',1} ...
    {'Exponent_e_LOGURA','Exponent_e_LOGURA','numeric',2} ...
    }});



reg.BlockChampagne = struct( ...
    'parent','sparse', ...
    'title','BlockChampagne Settings', ...
    'params',{{
    {'AtlasConstraints','AtlasConstraints','numeric',0}
    {'NeighborOrder','NeiborOrder','numeric',1}
    {'LearnNoise','LearnNoise','dropdown','true',{'true','false'}}
    {'NoiseObservationMatrix','NoiseObservation','dropdown','eye',{'eye'}}
    }});

reg.Champagne = struct( ...
    'parent','sparse', ...
    'title','Champagne Settings', ...
    'params',{{
    {'PruneThreshold','PruneThreshold','numeric',1e-6}
    {'UpdateNoise','UpdateNoise','dropdown','true',{'true','false'}}
    {'MaxIterations','MaxIterations','numeric',100}
    {'Tolerance','Tolerance','numeric', 1e-8}
    }});

reg.TS_Champagne = struct( ...
    'parent','sparse', ...
    'title','Lq_ADMM Settings', ...
    'params',{{}});
%  'customBuilder','No need');

reg.Lq_ADMM = struct( ...
    'parent','sparse', ...
    'title','Lq_ADMM Settings', ...
    'params',{{
    {'RegularizationParameter','RegParam','numeric',0.1}...
    {'DataFidelity','DataFidelity','edit','L2'}...
    {'ADMM_Rho','ADMM_Rho','numeric', 1}...
    {'q_norm','q_norm','numeric',0.5} ...
    {'MaxIterations','MaxIterations','numeric',500} ...
    {'Tolerance','Tolerance','numeric', 1e-5} ...
    }});
%   'customBuilder','Phi');

reg.uSTAR = struct( ...
    'parent','spatio', ...
    'title','uSTAR Settings', ...
    'params',{{
    {'NumTBFs','NumTBFs','numeric',4}
    {'uSTARRunAlgorithm','RunAlgorithm','dropdown','STAR',{'STAR','sSTARTS'}}
    % 特殊控件单独标记，引擎跳过，由专用方法补
    }});
% 'customBuilder','builduSTARExtras');   % 处理 MicrostateMaps 这种非标准控件


reg.STARTS = struct( ...
    'parent','spatio', ...
    'title','STARTS Settings', ...
    'params',{{
    {'NumTBFs','NumTBFs','numeric',4}
    {'NeighborOrder','NeiborOrder','numeric',1}
    {'LearnNoise','LearnNoise','dropdown','true',{'true','false'}}
    {'NoiseObservationMatrix','NoiseObservation','dropdown','eye',{'eye'}}
    }});

reg.BESTIES = struct( ...
    'parent','spatio', ...
    'title','BESTIES Settings', ...
    'params',{{
    {'InitialTau','InitialTau','numeric',0.99}
    {'LearnTau','LearnTau','dropdown','true',{'true','false'}}
    {'ComputeFreeEnergy','ComputeFreeEnergy','dropdown','true',{'true','false'}}
    {'NoiseObservationMatrix','NoiseObservation','dropdown','eye',{'eye'}}
    {'MaxIterations','MaxIterations','numeric',200}
    {'Tolerance','Tolerance','numeric', 1e-6}
    }});

reg.MxNE = struct( ...
    'parent','spatio', ...
    'title','MxNE Settings', ...
    'params',{{
    {'Alpha','Alpha','numeric',50}
    {'WeightsMin','WeightsMin','numeric',0.0}
    {'SolverMaxIter','SolverMaxIter','numeric',3000}
    {'SolverTolerance','SolverTolerance','numeric',1e-4}
    {'DebiasMaxIter','DebiasMaxIter','numeric',1000}
    {'DebiasTolerance','DebiasTolerance','numeric',1e-7}
    {'SolverMaxIter','SolverMaxIter','numeric',3000}
    {'Debias','Debias','dropdown','true',{'true','false'}}
    {'PCAWhitening','PCAWhitening','dropdown','true',{'true','false'}}
    }});
%DepthBiasComp,PickOri,Weights

reg.irMxNE = struct( ...
    'parent','spatio', ...
    'title','irMxNE Settings', ...
    'params',{{
    {'Alpha','Alpha','numeric',50}
    {'NumIRMXNEIter','NumIRMXNEIter','numeric',5}
    {'WeightsMin','WeightsMin','numeric',0.0}
    {'SolverMaxIter','SolverMaxIter','numeric',3000}
    {'SolverTolerance','SolverTolerance','numeric',1e-4}
    {'IRMXNETolerance','IRMXNETolerance','numeric',1e-4}
    {'DebiasMaxIter','DebiasMaxIter','numeric',1000}
    {'DebiasTolerance','DebiasTolerance','numeric',1e-7}
    {'SolverMaxIter','SolverMaxIter','numeric',3000}
    {'Debias','Debias','dropdown','true',{'true','false'}}
    {'PCAWhitening','PCAWhitening','dropdown','true',{'true','false'}}
    }});
%DepthBiasComp,RankNoiseCov,PickOri,Weights


reg.FASTIRES = struct( ...
    'parent','spatio', ...
    'title','FASTIRES Settings', ...
    'params',{{
    {'Alpha','Alpha','numeric',50}
    {'NumTBFs','NumTBFs','numeric',4}
    {'Epsilon','Epsilon','numeric',1e-3}
    {'MaxIterations','MaxIterations','numeric',10}
    {'MaxInnerIterationsX','MaxInnerIterationsX','numeric',20}
    {'MaxInnerIterationsY','MaxInnerIterationsY','numeric',20}
    {'MaxInnerIterationsProj','MaxInnerIterationsProj','numeric',20}
    {'Tolerance','Tolerance','numeric',1e-4}
    }});%InitialTBFs

reg.dMAP = struct( ...
    'parent','spatio', ...
    'title','dMAP Settings', ...
    'params',{{
    {'lambda_F','lambda_F','numeric',0.95}
    {'alpha_F','alpha_F','numeric',0.51}
    {'max_iter','max_iter','numeric',15}
    {'tol','tol','numeric',1e-5}
    }});%InitialSourceCovDiag


reg.debiased_GroupLasso = struct( ...
    'parent','spatio', ...
    'title','debiased_GroupLasso Settings', ...
    'params',{{
    {'RegularizationParameter','RegParam','numeric',0.1}
    {'DynamicLambda','DynamicLambda','dropdown','true',{'true','false'}}
    {'JointEstNum','JointEstNum','numeric',10}
    {'Debias','Debias','dropdown','true',{'true','false'}}
    {'MaxIterations','MaxIterations','numeric',10}
    {'Tolerance','Tolerance','numeric', 1e-4}
    }});

reg.SISSY_L21 = struct( ...
    'parent','spatio', ...
    'title','SISSY_L21 Settings', ...
    'params',{{
    {'lambda','lambda','numeric',1.0}
    {'DynamicLambda','DynamicLambda','dropdown','true',{'true','false'}}
    {'JointEstNum','JointEstNum','numeric',10}
    {'alpha','alpha','numeric',0.51}
    {'rho','rho','numeric',1.0}
    {'max_iter','max_iter','numeric',15}
    {'tol','tol','numeric',1e-5}
    }});

reg.TFMxNE = struct( ...
    'parent','spatio', ...
    'title','TFMxNE Settings', ...
    'params',{{
    {'SpatialReg','SpatialReg','numeric',90}
    {'TemporalReg','TemporalReg','numeric',30}
    {'TimeStep','TimeStep','numeric',4}
    {'WindowSize','WindowSize','numeric',80}
        {'MaxIterations','MaxIterations','numeric',50}
    {'Tolerance','Tolerance','numeric', 1e-3}
    }});

reg.MCMV = struct( ...
    'parent','beamformer', ...
    'title','MCMV Settings', ...
    'params',{{
    {'RegularizationParameter','RegParam','numeric',0.05}
    }});%DataCovariance,EvokedCovariance

reg.LCMV = struct( ...
    'parent','beamformer', ...
    'title','LCMV Settings', ...
    'params',{{
       {'Type','Type','edit','ug'}
        {'RegularizationParameter','RegParam','numeric',0.05}
        {'ScalarBeamformer','ScalarBeamformer','dropdown','true',{'true','false'}}
    }});%DataCovariance


end